steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - function-18
  - --source=https://source.developers.google.com/projects/jackpot-fefff/repos/github_teletha_cointoss-functions
  - --trigger-http